#!/bin/bash

if [ $# -ge 2 ]
then
	liste=`ls $2`
else
	liste=`ls`
fi

var=`date`
for name in $liste
do
	if [ -f $name ]
	then
		git add $name
	fi
done

if [ $# -ge 1 ]
then 
	git commit -m $1
else
	git commit -m "commit du $var"
fi
