#!/bin/bash

declare -A file=([labels]=`ls labels` [images]=`ls images`)

for type in labels images
do
	echo ">>>>>> $type"
	for name in ${file[$type]}
	do
		file=`basename $name .mgz`
		mri_convert $type/$file.mgz $type/$file.nii.gz
	done
	rm $type/fs*
	rm $type/*mgz
done
