#! /bin/bash

echo ''
if [ -d FS_outputs ]
then
  echo '>>>>>>>>>> it is ok'
else
  echo '>>>>>>>>>> extract'
  unzip ~/Documents/labels.zip
fi

echo ''
echo '>>>>>>>>>> purge'
rm -r images labels labels_bin
mkdir images labels labels_bin

echo ''
echo '>>>>>>>>>> deplacement'
bash $1

echo ''
echo '>>>>>>>>>> convert'
bash convert

echo ''
echo '>>>>>>>>>> binarisation'
python binarisation.py
