#! /bin/bash

dir='FS_outputs'

liste=`ls $dir`
declare -A file=(["labels"]="ribbon" ["images"]="orig")

for name in $liste
do
	for type in labels images
	do
		cp $dir/$name/mri/${file[$type]}.mgz $type/$name-${file[$type]}.mgz
	done
done
