#!/bin/bash

calc()
{
	awk "BEGIN{print $*}";
}

type=$1
version=version\_$2
name=$3\_mom
path=/home/julien/traineeship/mmiv/$type
model=$path/model
doc=/home/julien/documents/results/$version
mom=$model/logs/$version

if [ ! -d $doc ]
then
	mkdir -p $doc
fi

if [ ! -d $mom ]
then
	mkdir -p $mom
fi

k=0
racine="$doc/$version_$name"
fold=$racine\_$k
while [ -d $fold ]
do
	k=`calc $k+1`
	fold=$racine\_$k
done
mkdir -p $fold

mv $path/outputs $fold
mv $model/models $fold
mv $model/*g $fold
mv $model/*v $fold
mv $model/s* $fold


i=0
while [ ! -d $model/logs/$i ]
do
	i=`calc $i+1`
done
mv $model/logs/$i $mom/$name\_$k
