#!/bin/bash

pati=/home/julien/traineeship/mmiv/
pato=`pwd`
cd $pati

calc()
{
	awk "BEGIN{print $*}";
}

if [ $# -gt 0 ]
then
	if [ $1 = training ]
	then
		cp app/decay_lr_application_$2.py ~/.conda/envs/niftynet/lib/python3.7/site-packages/niftynet/contrib/learning_rate_schedule/decay_lr_application.py
  		net_run train -a niftynet.contrib.learning_rate_schedule.decay_lr_application.DecayLearningRateApplication -c config/nn_demo.ini
  		cat model/training_niftynet_log | grep CRITICAL
	elif [ $1 = train ]
	then
		net_segment train -c config/nn_demo.ini
	elif [ $1 = inference ]
	then
		net_segment inference -c config/nn_demo.ini
	elif [ $1 = evaluation ]
	then
		net_segment evaluation -c config/nn_demo.ini
	elif [ $1 = 'help' ]
	then	
		liste=`ls app | grep decay`
		train=-1
		infer=0
		for k in $liste
		do
			train=`calc $train+1`
		done
		liste=`ls config | grep infer`
		for k in $liste
		do
			infer=`calc $infer+1`
		done
		echo "the first argument should be training, inference, evaluation or train"
		echo "if the first argument isn't train, the command should have a second argument"
		echo "for training, the second argument is between 0 and $train"
		echo "for inference and evaluation it is between 1 and $infer"
	else
		echo "You did a very bad mistake"
	fi
else
	echo "You miss a good thing"
fi
cd $pato
