#!/bin/bash

if [ $1 = help ]
then
	echo "usage : master labels datas_type"
	echo "the type of labels are the name of folders in the config folder"
	ls "momentum/config"
	echo "the type of data are in the previous folder : it's the name of this file whithout suffix and prefix"

	liste=`ls momentum/config/binary_brain`
	for name in $liste
	do
		name=`basename ${name#conf_} .ini`
		echo $name
	done
else
	labels=$2
	data=$3
	type=$1
	path=/home/julien/traineeship/mmiv/$type
	rm $path/model/histog*

	bash ./train $type $labels $data
	bash ./dpl $type static $labels\_$data

	liste=`ls $path/app`

	for name in $liste
	do
		app=`basename ${name#decay_lr_application_} .py`
		bash ./training $type $labels $data $app
		bash ./dpl $type $app $labels\_$data
	done
fi
