#!/bin/bash

if [ $1 = help ]
then
	echo "usage : master labels datas_type"
	echo "the type of labels are the name of folders in the config folder"
	ls config
	echo "the type of data are in the previous folder : it's the name of this folder whithout suffix and prefix"

	liste=`ls config/binary_brain`
	for name in $liste
	do
		name=`basename ${name#conf_} .ini`
		echo $name
	done
else
	labels=$1
	data=$2
	path=/home/julien/traineeship/mmiv

	bash $path/train $labels $data
	bash $path/dpl static static\_$labels\_$data

	liste=`ls $path/app`

	for name in $liste
	do
		app=`basename ${name#decay_lr_application_} .py`
		bash $path/training $labels $data $app
		bash $path/dpl $app $app\_$labels\_$data
	done
fi
