#!/bin/bash

echo "do you want to shutdown the computer after this last nwork ?"
read confirmation
if [ confirmation = 'o' ]
then
	while [ `pgrep master` > 0 ]
	do
		touch pf
		rm pf
	done
	shutdown
fi
