#!/bin/bash

calc()
{
	awk "BEGIN{print $*}";
}

version=version\_$1
name=$2\_mom
path=/home/julien/traineeship/mmiv/momentum/model
doc=/home/julien/documents/results/$version
mom=$path/logs/$version

if [ ! -d $doc ]
then
	mkdir -p $doc
fi

if [ ! -d $mom ]
then
	mkdir -p $mom
fi

mv outputs $doc/$version\_$name
mv $path/models $doc/$version\_$name
mv $path/*g $doc/$version\_$name
mv $path/*v $doc/$version\_$name
mv $path/s* $doc/$version\_$name


i=0
while [ ! -d $path/logs/$i ]
do
	i=`calc $i+1`
done
mv $path/logs/$i $mom/$name
