#!/bin/bash

version=$1
name=$2\_mom
path=/home/julien/traineeship/mmiv/momentum/model
doc=/home/julien/documents/results/version\_$version

if [ -d $doc ]
then
	echo ""
else
	mkdir -p $doc
fi

if [ -d $path ]
then
	echo ""
else
	mkdir -p $path
fi

mv outputs $doc/$version\_$name
mv $path/models $doc/$version\_$name
mv $path/*g $doc/$version\_$name
mv $path/*v $doc/$version\_$name
mv $path/s* $doc/$version\_$name
mv $path/logs/0 $path/logs/version\_$version/$name
